project:
  name: quickstart-hail
  regions:
    - us-east-1
  parameters:
      KMSEbsKeyArn: ''
      pS3packerZipLocation: ami/packer.zip
      HailS3BucketName: hail-$[taskcat_autobucket]
      SageMakerS3BucketName: sg-$[taskcat_autobucket]
      VPCSubnetType: private
      TagOwner: ''
      TagEnvironmentType: development
      CreateHailBucket: "yes"
      CreateSageMakerBucket: "yes"
      QSS3BucketName: $[taskcat_autobucket]

tests:
  vpcNew:
    parameters:
      VPCTarget: new
      VPCCIDR: 10.0.0.0/16
      VPCId: ''
      VPCSubnetId: ''
      VPCSubnetType: private
    template: ./templates/hail-master.yml
