AWSTemplateFormatVersion: "2010-09-09"
Description: "Hail S3 Resources (qs-1qp776mhl)"

Parameters:

  pHailBucket:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "EMR logs, cluster manifests, and VEP configuration files are placed here."
    Type: "String"

  pCreateHailBucket:
    Type: "String"
    Description: "Select No to use an existing bucket."
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"

  pSageMakerBucket:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "Bucket for common Jupyter notebooks and SageMaker home directory backups."
    Type: "String"

  pCreateSageMakerBucket:
    Type: "String"
    Description: "Select No to use an existing bucket."
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"

  pTagEnvironment:
    AllowedValues:
      - "production"
      - "staging"
      - "development"
      - ""
    Default: ""
    Description: "(Optional) Environment type for default resource tagging."
    Type: "String"

  pTagOwner:
    Type: "String"
    Description: "Optional - Owner of the resources.  Person/Department, etc."
    Default: ""


Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Bucket Details"
        Parameters:
          - "pHailBucket"
          - "pCreateHailBucket"
          - "pSageMakerBucket"
          - "pCreateSageMakerBucket"
      - Label:
          default: "Tagging"
        Parameters:
          - "pTagOwner"
          - "pTagEnvironment"
    ParameterLabels:
      pHailBucket:
        default: "Hail Bucket Name"
      pCreateHailBucket:
        default: "Create Hail Bucket"
      pSageMakerBucket:
        default: "Sagemaker Home Directory Bucket Name"
      pCreateSageMakerBucket:
        default: "Create SageMaker Bucket"
      pTagOwner:
        default: "Owner Tag"
      pTagEnvironment:
        default: "Environment Tag"

Conditions:

    createHailBucket: !Equals  [!Ref pCreateHailBucket, "yes"]
    createSageMakerBucket: !Equals  [!Ref pCreateSageMakerBucket, "yes"]

Resources:

  sagemakerBucket:
    Type: "AWS::S3::Bucket"
    Condition: createSageMakerBucket
    Properties:
      BucketName: !Ref pSageMakerBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      #FIXME - REMOVE before uploading to GitHub
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      Tags:
        - Key: "environment"
          Value: !Ref pTagEnvironment
        - Key: "owner"
          Value: !Ref pTagOwner
    #FIXME - Change to Retain before updating Github
    #DeletionPolicy: Retain

  sageMakerBucketParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "S3 bucket with Jupyter scripts, common notebooks, and home directory backups."
      Name: "/hail/s3/sagemaker"
      Type: "String"
      Value: !Ref pSageMakerBucket

  hailBucket:
    Type: "AWS::S3::Bucket"
    Condition: createHailBucket
    Properties:
      BucketName: !Ref pHailBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      #FIXME - REMOVE before uploading to GitHub
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      Tags:
        - Key: "environment"
          Value: !Ref pTagEnvironment
        - Key: "owner"
          Value: !Ref pTagOwner
    #FIXME - Change to Retain before updating GitHub
    #DeletionPolicy: Retain



  hailBucketParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "S3 bucket for cluster manifest outputs."
      Name: "/hail/s3/hail"
      Type: "String"
      Value: !Ref pHailBucket

Outputs:

  bucketHail:
    Description: "Hail S3 Bucket"
    Value: !Ref pHailBucket

  bucketSageMaker:
    Description: "SageMaker S3 Bucket"
    Value: !Ref pSageMakerBucket
